# Generated by Django 3.2.15 on 2022-10-05 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_userfollowers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserFollowers',
            new_name='UserFollower',
        ),
    ]
