# Generated by Django 3.2.15 on 2022-10-14 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_alter_userfollower_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='following', to='network.UserFollower'),
        ),
    ]
