# Generated by Django 3.2.15 on 2022-10-14 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_user_following'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='following',
        ),
    ]
