# Generated by Django 3.2.15 on 2022-10-14 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_remove_user_following'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userfollower',
            old_name='follower',
            new_name='follower_id',
        ),
        migrations.RenameField(
            model_name='userfollower',
            old_name='user',
            new_name='user_id',
        ),
    ]
