# Generated by Django 3.2.15 on 2022-10-14 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_auto_20221014_0227'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userfollower',
            old_name='follower_id',
            new_name='follower',
        ),
        migrations.RenameField(
            model_name='userfollower',
            old_name='user_id',
            new_name='user',
        ),
    ]
